services:
  backend:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    environment:
      - MONDODB_URI=mongodb://sabsunno:sabsunno@mongodb:27017/
  mongodb:
    image: mongo
    restart: always
    container_name: sabsunno-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: sabsunno
      MONGO_INITDB_ROOT_PASSWORD: sabsunno
    ports:
      - 27017:27017
    volumes:
      - ./db_data/:/data/db/
